### ISSUE TITLE
Gracefully dispatching multiple actions on load - based on reducer structure

### ISSUE THREAD

**Issue by tamethecomplex** [jportela/redux-saga-persistence#1]
Hi João,

First off, thanks so much for this repo and for your corresponding blog post - it has been extremely helpful in getting persistence off the ground for my react/redux project.

One question regarding dispatching actions to the reducers on SERVER_LOAD_SUCCESS.  When retrieving initial state from the PersistenceEngine and dispatching an action to the reducers:

```javascript
const state = yield call(PersistenceEngine.load);
yield put(serverLoad.success(state));
```

Is there a way to capture the SERVER_LOAD_SUCCESS action in a given reducer without fully specifying the piece of the action payload to assign the initial state?

In other words, instead of writing this in a given reducer:

```javascript
function sqlText(state = initialState.sqlText, action) {
  switch(action.type) {
    case types.SERVER_LOAD_SUCCESS:
      return action.payload.user_data.consoleInputPanel.sqlText
```

You could write this?:

```javascript
function sqlText(state = initialState.sqlText, action) {
  switch(action.type) {
    case types.SERVER_LOAD_SUCCESS:
      return action.sqlText
```

One way to deal with this would be to dispatch different actions for different pieces of the state, but I was wondering if in your experience, you have come up with a way to accomplish this in a way that if reducer structure changes, it's not necessary to refactor the load logic.

**Comment by jportela** [comment]
Hi @complsci, glad you liked it!

I see how the workflow you suggest might be useful and I think it's possible, by using your own top level reducer (instead of the combineReducers from Redux). There's a video by @gaearon explaining how to implement combineReducers from scratch here, which might help you into writing your variation that will accomplish the behaviour you want: https://egghead.io/lessons/javascript-redux-implementing-combinereducers-from-scratch

I usually just "select" the substate I need from the payload (which is basically what you do here: `return action.payload.user_data.consoleInputPanel.sqlText`).

**Comment by tamethecomplex** [comment]
Hi João, thanks for your response and the video link, I will check it out!
